apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: attendee-web
  namespace: attendee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: attendee-web
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: attendee-worker
  namespace: attendee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: attendee-worker
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
