apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: bots-high-priority
value: 100000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "High priority for bursty on-demand bot pods to speed up scheduling during scale-out."
